-- P2/P3: durable bidirectional sync tasks and conflict work items.
CREATE TABLE IF NOT EXISTS user_bgm_collection_sync_task (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '同步任务主键',
  user_id BIGINT NOT NULL COMMENT 'AnimeFlow 用户 ID',
  subject_type TINYINT NOT NULL COMMENT '条目大类：1漫画、2动画、3音乐、4游戏、6三次元',
  bgm_account_uid BIGINT NULL COMMENT '本次任务目标 Bangumi 用户 UID，换绑后不可复用',
  oauth_id BIGINT NULL COMMENT '本次任务使用的 user_oauth 绑定记录 ID',
  request_id VARCHAR(80) NOT NULL COMMENT '客户端幂等请求 ID',
  status ENUM('QUEUED','RUNNING','WAITING_CONFLICT','PARTIAL_FAILED','SUCCESS','FAILED','CANCELLED') NOT NULL COMMENT '任务状态',
  phase ENUM('SCANNING','APPLYING','RESOLVING') NOT NULL COMMENT '执行阶段',
  total_count INT NOT NULL DEFAULT 0 COMMENT '本次任务去重后的条目总数',
  imported_count INT NOT NULL DEFAULT 0 COMMENT '从 Bangumi 导入到本地的条目数',
  uploaded_count INT NOT NULL DEFAULT 0 COMMENT '从本地上传到 Bangumi 的条目数',
  unchanged_count INT NOT NULL DEFAULT 0 COMMENT '双方数据一致、无需更新的条目数',
  conflict_count INT NOT NULL DEFAULT 0 COMMENT '等待用户处理的冲突数',
  resolved_count INT NOT NULL DEFAULT 0 COMMENT '已完成决议并确认同步的冲突数',
  failed_count INT NOT NULL DEFAULT 0 COMMENT '处理失败、可重试的条目数',
  status_version BIGINT NOT NULL DEFAULT 0 COMMENT '任务状态版本，用于客户端判断状态是否变化',
  error_code ENUM('SYNC_BINDING_CHANGED','SYNC_RETRY_REQUIRED') NULL COMMENT '任务级错误码',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '任务入库时间',
  started_at DATETIME(3) NULL COMMENT '任务首次开始执行时间',
  finished_at DATETIME(3) NULL COMMENT '任务进入终态的时间',
  heartbeat_at DATETIME(3) NULL COMMENT '后台执行器最近一次续租/心跳时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_collection_sync_request (user_id, request_id),
  KEY idx_collection_sync_active (user_id, status, id),
  KEY idx_collection_sync_cleanup (status, finished_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户 Bangumi 收藏双向同步任务';

CREATE TABLE IF NOT EXISTS user_bgm_collection_sync_item (
  id BIGINT NOT NULL AUTO_INCREMENT COMMENT '同步明细主键，同时作为客户端冲突 ID',
  task_id BIGINT NOT NULL COMMENT '所属同步任务 ID',
  user_id BIGINT NOT NULL COMMENT 'AnimeFlow 用户 ID，用于归属校验',
  subject_id INT NOT NULL COMMENT 'Bangumi 条目 ID',
  subject_type TINYINT NOT NULL COMMENT '条目大类，必须与任务目标类型一致',
  subject_name VARCHAR(512) NULL COMMENT '冲突发生时的条目名称快照',
  subject_image VARCHAR(1024) NULL COMMENT '冲突发生时的条目封面地址快照',
  local_type TINYINT NULL COMMENT '冲突发生时本地收藏分类，1至5',
  remote_type TINYINT NULL COMMENT '冲突发生时 Bangumi 收藏分类，1至5',
  local_version BIGINT NULL COMMENT '冲突发生时本地收藏乐观锁版本',
  conflict_version BIGINT NOT NULL DEFAULT 1 COMMENT '冲突快照版本，提交决议时必须匹配',
  selected_type TINYINT NULL COMMENT '用户选择的最终收藏分类，决议入库前为空',
  local_snapshot JSON NULL COMMENT '冲突发生时的本地收藏字段快照，不包含凭据',
  remote_snapshot JSON NULL COMMENT '冲突发生时的 Bangumi 收藏字段快照，不包含凭据',
  status ENUM('PLANNED','CONFLICT','RESOLUTION_PENDING','APPLY_PENDING','DONE','FAILED') NOT NULL COMMENT '明细状态',
  error_code VARCHAR(64) NULL COMMENT '明细错误码，不保存 token 或完整私密内容',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '明细创建时间',
  resolved_at DATETIME(3) NULL COMMENT '远端确认并完成本地回写的时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_collection_sync_item (task_id, subject_id),
  KEY idx_collection_sync_conflict (user_id, status, id),
  CONSTRAINT fk_collection_sync_item_task FOREIGN KEY (task_id) REFERENCES user_bgm_collection_sync_task(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户 Bangumi 收藏同步明细与冲突快照';
