server:
  port: 1024
spring:
  application:
    name: AnimeFlow-Service
  config:
    import: optional:file:.env[.properties]
#  data:
#    redis:
#      host: 154.194.253.58
#      port: 6379
#      password: 200309
#      username:
bangumi:
  client_id: bgm5267694605415a325
  client_secret: 19fef4c5b30a7fe3c7ee21e049dd5b22
  redirect_uri: https://ligg.top/oauth/callback
