CREATE TABLE `user_bgm_collection`  (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `user_id` bigint NOT NULL COMMENT 'AnimeFlow 用户 ID，关联 user.id',
  `subject_id` int NOT NULL COMMENT 'Bangumi 条目 ID，关联 bgm_subject.id',
  `subject_type` tinyint UNSIGNED NOT NULL DEFAULT 2 COMMENT '条目大类：1漫画 2动画 3音乐 4游戏 6三次元',
  `images` json NULL COMMENT '条目封面图 {large,common,medium,small,grid}',
  `bgm_interest_id` bigint NOT NULL COMMENT 'Bangumi 收藏记录 ID（interest.id）',
  `rate` tinyint NOT NULL DEFAULT 0 COMMENT '用户评分 0-10，0 表示未评分',
  `type` tinyint NOT NULL COMMENT '收藏类型 1=想看 2=看过 3=在看 4=搁置 5=抛弃',
  `comment` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '收藏评论',
  `tags` json NULL COMMENT '收藏标签 JSON 数组',
  `ep_status` smallint UNSIGNED NOT NULL DEFAULT 0 COMMENT '已看话数（interest.epStatus）',
  `vol_status` smallint UNSIGNED NOT NULL DEFAULT 0 COMMENT '已看卷数（interest.volStatus）',
  `is_private` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否私密收藏（interest.private）',
  `bgm_updated_at` bigint NOT NULL COMMENT 'Bangumi 收藏更新时间 Unix 秒（interest.updatedAt）',
  `sync_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后同步时间',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '首次入库时间',
  `private` tinyint(1) NULL DEFAULT 0,
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_bgm_interest_id`(`bgm_interest_id` ASC) USING BTREE COMMENT 'Bangumi 收藏 ID 唯一',
  UNIQUE INDEX `uk_user_subject`(`user_id` ASC, `subject_id` ASC) USING BTREE COMMENT '同一用户对同一条目仅一条收藏',
  INDEX `idx_user_type`(`user_id` ASC, `type` ASC) USING BTREE,
  INDEX `idx_subject_id`(`subject_id` ASC) USING BTREE,
  INDEX `idx_user_type_updated`(`user_id` ASC, `type` ASC, `bgm_updated_at` DESC) USING BTREE,
  INDEX `idx_user_type_subject_updated`(`user_id` ASC, `type` ASC, `subject_type` ASC, `bgm_updated_at` DESC) USING BTREE,
  INDEX `idx_user_sync_time`(`user_id` ASC, `sync_time` ASC) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 375 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci COMMENT = '用户 Bangumi 收藏关系表' ROW_FORMAT = DYNAMIC;
CREATE TABLE `bangumi_subject`  (
  `id` int UNSIGNED NOT NULL COMMENT '条目 ID',
  `type` tinyint UNSIGNED NOT NULL COMMENT '作品类型：1漫画 2动画 3音乐 4游戏 6三次元',
  `name` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '条目名',
  `name_cn` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '条目简体中文名',
  `infobox` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '原始 wiki 字符串',
  `platform` smallint UNSIGNED NOT NULL DEFAULT 0 COMMENT '条目平台',
  `summary` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '条目简介',
  `nsfw` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否 NSFW',
  `tags` json NULL COMMENT '标签列表 [{name,count}]',
  `meta_tags` json NULL COMMENT '公共标签列表',
  `score` decimal(4, 1) NULL DEFAULT NULL COMMENT '评分',
  `score_details` json NULL COMMENT '评分分布 {1..10: count}',
  `rank` int UNSIGNED NULL DEFAULT NULL COMMENT '类别内排名',
  `date` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '发行日期',
  `favorite` json NULL COMMENT '收藏状态 {wish,done,doing,on_hold,dropped}',
  `series` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否为系列作品',
  `images` json NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `idx_type_nsfw`(`type` ASC, `nsfw` ASC) USING BTREE,
  INDEX `idx_bgm_rank`(`rank` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = 'Bangumi 条目' ROW_FORMAT = Dynamic;